# Generated by Django 2.2 on 2020-01-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_updated_date',
            field=models.CharField(blank=True, max_length=108, null=True, verbose_name='最近更新时间时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.CharField(blank=True, max_length=108, null=True, verbose_name='下单时间'),
        ),
    ]
